### PR TITLE
video: remove duplicated inclusion in Kconfig

### PR DESCRIPTION
**Pull request by fnadeau**
Removed duplicate inclusion of mxc/Kconfig, this made menuconfig display three times the same configuration setting.

### CODE REVIEW

**Comment by gibsson** [comment]
Hi,
Thanks for your patch! Can you add a SOB? Then I'll merge it.
Thanks,
Gary

**Comment by gibsson** [comment]
Also, please change the subject to be more explicit, like:
video: remove duplicated inclusion in Kconfig

Thanks,
Gary

**Comment by fnadeau** [comment]
I'm not quite sure I understand you request to "add a SOB". As far as I understand it, this patch will affect any iMX6 devices, ours is a derivative work from the Nitrogen6X.

**Comment by gibsson** [comment]
SOB stands for "Signed-off-by", in order to follow the standard patch submission rules:
https://www.kernel.org/doc/Documentation/SubmittingPatches

Regards,
Gary

**Comment by fnadeau** [comment]
Fixed, thanks for the explanation.

**Comment by gibsson** [comment]
Thanks for your patch!

Regards,
Gary

**Pull request merged**
